"""add client available_cities client_order

Revision ID: e540edf560c0
Revises: d7123ce5bd7e
Create Date: 2023-12-17 15:55:18.828484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e540edf560c0"
down_revision: Union[str, None] = "d7123ce5bd7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_order",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("arrival_date", sa.Date(), nullable=False),
        sa.Column("departure_city", sa.String(), nullable=False),
        sa.Column("arrival_city", sa.String(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arrival_city"],
            ["available_cities.name"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["departure_city"],
            ["available_cities.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client_order")
    # ### end Alembic commands ###
